export const SET_TICKET_DATA = 'SET_TICKET_DATA';

export const FETCH_TICKET_DATA_REQUEST = 'FETCH_TICKET_DATA_REQUEST';
export const FETCH_TICKET_DATA_SUCCESS = 'FETCH_TICKET_DATA_SUCCESS';
export const FETCH_TICKET_DATA_FAILURE = 'FETCH_TICKET_DATA_FAILURE';

export const ADD_TAG_TO_TICKET_REQUEST = 'ADD_TAG_TO_TICKET_REQUEST';
export const ADD_TAG_TO_TICKET_SUCCESS = 'ADD_TAG_TO_TICKET_SUCCESS';
export const ADD_TAG_TO_TICKET_FAILURE = 'ADD_TAG_TO_TICKET_FAILURE';

export const SET_TICKET_PRIORITY_REQUEST = 'SET_TICKET_PRIORITY_REQUEST';
export const SET_TICKET_PRIORITY_SUCCESS = 'SET_TICKET_PRIORITY_SUCCESS';
export const SET_TICKET_PRIORITY_FAILURE = 'SET_TICKET_PRIORITY_FAILURE';