export const SET_TICKET_DATA = 'SET_TICKET_DATA';

export const FETCH_TICKET_DATA_REQUEST = 'FETCH_TICKET_DATA_REQUEST';
export const FETCH_TICKET_DATA_SUCCESS = 'FETCH_TICKET_DATA_SUCCESS';
export const FETCH_TICKET_DATA_FAILURE = 'FETCH_TICKET_DATA_FAILURE';