export const SET_TICKET_DATA = 'SET_TICKET_DATA';

export const FETCH_TICKET_DATA_REQUEST = 'FETCH_TICKET_DATA_REQUEST';
export const FETCH_TICKET_DATA_SUCCESS = 'FETCH_TICKET_DATA_SUCCESS';
export const FETCH_TICKET_DATA_FAILURE = 'FETCH_TICKET_DATA_FAILURE';

export const SAVE_TICKET_TAGS_REQUEST = 'SAVE_TICKET_TAGS_REQUEST';
export const SAVE_TICKET_TAGS_SUCCESS = 'SAVE_TICKET_TAGS_SUCCESS';
export const SAVE_TICKET_TAGS_FAILURE = 'SAVE_TICKET_TAGS_FAILURE';

export const SET_TICKET_PRIORITY_REQUEST = 'SET_TICKET_PRIORITY_REQUEST';
export const SET_TICKET_PRIORITY_SUCCESS = 'SET_TICKET_PRIORITY_SUCCESS';
export const SET_TICKET_PRIORITY_FAILURE = 'SET_TICKET_PRIORITY_FAILURE';

export const SET_TICKET_ASSIGNED_TO_REQUEST = 'SET_TICKET_ASSIGNED_TO_REQUEST';
export const SET_TICKET_ASSIGNED_TO_SUCCESS = 'SET_TICKET_ASSIGNED_TO_SUCCESS';
export const SET_TICKET_ASSIGNED_TO_FAILURE = 'SET_TICKET_ASSIGNED_TO_FAILURE';

export const SET_TICKET_TIME_ESTIMATE_REQUEST = 'SET_TICKET_TIME_ESTIMATE_REQUEST';
export const SET_TICKET_TIME_ESTIMATE_SUCCESS = 'SET_TICKET_TIME_ESTIMATE_SUCCESS';
export const SET_TICKET_TIME_ESTIMATE_FAILURE = 'SET_TICKET_TIME_ESTIMATE_FAILURE';

export const SET_TICKET_DESCRIPTION_REQUEST = 'SET_TICKET_DESCRIPTION_REQUEST';
export const SET_TICKET_DESCRIPTION_SUCCESS = 'SET_TICKET_DESCRIPTION_SUCCESS';
export const SET_TICKET_DESCRIPTION_FAILURE = 'SET_TICKET_DESCRIPTION_FAILURE';

export const SET_TICKET_NAME_REQUEST = 'SET_TICKET_NAME_REQUEST';
export const SET_TICKET_NAME_SUCCESS = 'SET_TICKET_NAME_SUCCESS';
export const SET_TICKET_NAME_FAILURE = 'SET_TICKET_NAME_FAILURE';

export const ADD_TICKET_COMMENT_REQUEST = 'ADD_TICKET_COMMENT_REQUEST';
export const ADD_TICKET_COMMENT_SUCCESS = 'ADD_TICKET_COMMENT_SUCCESS';
export const ADD_TICKET_COMMENT_FAILURE = 'ADD_TICKET_COMMENT_FAILURE';

export const EDIT_TICKET_COMMENT_REQUEST = 'EDIT_TICKET_COMMENT_REQUEST';
export const EDIT_TICKET_COMMENT_SUCCESS = 'EDIT_TICKET_COMMENT_SUCCESS';
export const EDIT_TICKET_COMMENT_FAILURE = 'EDIT_TICKET_COMMENT_FAILURE';

export const DELETE_TICKET_COMMENT_REQUEST = 'DELETE_TICKET_COMMENT_REQUEST';
export const DELETE_TICKET_COMMENT_SUCCESS = 'DELETE_TICKET_COMMENT_SUCCESS';
export const DELETE_TICKET_COMMENT_FAILURE = 'DELETE_TICKET_COMMENT_FAILURE';