export const SET_PROJECT_DATA = 'SET_PROJECT_DATA';
export const SET_PROJECT_DETAILS = 'SET_PROJECT_DETAILS';

export const FETCH_PROJECT_DETAILS_REQUEST = 'FETCH_PROJECT_DETAILS_REQUEST';
export const FETCH_PROJECT_DETAILS_SUCCESS = 'FETCH_PROJECT_DETAILS_SUCCESS';
export const FETCH_PROJECT_DETAILS_FAILURE = 'FETCH_PROJECT_DETAILS_FAILURE';

export const UPDATE_PROJECT_DETAILS_REQUEST = 'UPDATE_PROJECT_DETAILS_REQUEST';
export const UPDATE_PROJECT_DETAILS_SUCCESS = 'UPDATE_PROJECT_DETAILS_SUCCESS';
export const UPDATE_PROJECT_DETAILS_FAILURE = 'UPDATE_PROJECT_DETAILS_FAILURE';

export const DELETE_PROJECT_COLUMN_REQUEST = 'DELETE_PROJECT_COLUMN_REQUEST';
export const DELETE_PROJECT_COLUMN_SUCCESS = 'DELETE_PROJECT_COLUMN_SUCCESS';
export const DELETE_PROJECT_COLUMN_FAILURE = 'DELETE_PROJECT_COLUMN_FAILURE';

export const FETCH_ARCHIVED_TICKETS_REQUEST = 'FETCH_ARCHIVED_TICKETS_REQUEST';
export const FETCH_ARCHIVED_TICKETS_SUCCESS = 'FETCH_ARCHIVED_TICKETS_SUCCESS';
export const FETCH_ARCHIVED_TICKETS_FAILURE = 'FETCH_ARCHIVED_TICKETS_FAILURE';

export const RESTORE_TICKETS_REQUEST = 'RESTORE_TICKETS_REQUEST';
export const RESTORE_TICKETS_SUCCESS = 'RESTORE_TICKETS_SUCCESS';
export const RESTORE_TICKETS_FAILURE = 'RESTORE_TICKETS_FAILURE';

export const SET_ARCHIVED_TICKETS_REQUEST = 'SET_ARCHIVED_TICKETS_REQUEST';
export const SET_ARCHIVED_TICKETS_SUCCESS = 'SET_ARCHIVED_TICKETS_SUCCESS';
export const SET_ARCHIVED_TICKETS_FAILURE = 'SET_ARCHIVED_TICKETS_FAILURE';

export const DELETE_TICKETS_REQUEST = 'DELETE_TICKETS_REQUEST';
export const DELETE_TICKETS_SUCCESS = 'DELETE_TICKETS_SUCCESS';
export const DELETE_TICKETS_FAILURE = 'DELETE_TICKETS_FAILURE';